blank_issues_enabled: false
contact_links:
  - name: Tern Documentation
    url: https://github.com/zyf8827/tern/tree/main/docs
    about: Please check the official documentation before creating an issue.
